sudo : required

language : scala

scala :
  2.12.1

jdk :
  - oraclejdk8

branches :
  except :
    - dev

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - travis_wait 30 echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - travis_wait 30 sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - travis_wait 30 sudo apt-get update
  - travis_wait 30 sudo apt-get install sbt

before_install:
  - pip install --user codecov

script :
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash) -F unittest || echo "Codecov did not collect coverage reports"
