sudo : false

language : scala

scala :
  2.12.1

jdk :
  - oraclejdk8

branches :
  except :
    - dev

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

script :
  - sbt clean coverage test && sbt coverageAggregate
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm