[type.IP_ADDRESS]
value = "@.@.@.@" # implicit @1.@2.@3.@4
require = [
    "@ : Int",
    "@ >= 0",
    "@ <= 999"
]
declarators = [
    ["arduino","IPAddress @identifier(@1,@2,@3,@4);"],
    ["c","int @identifier [] = {@1,@2,@3,@4};"]
]

[type.MAC_ADDRESS]
value = "@:@:@:@:@:@:@:@"
require = [
    "@0 match [0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]"
]
declarators = [
    ["arduino" , "byte @identifier [] {@1,@2,@3,@4,@5,@6,@7,@8};"],
    ["c" , "byte @identifier [] {@1,@2,@3,@4,@5,@6,@7,@8};"]
]

[type.PORT]
value = "@"
require = [
    "@ : Int",
    "@ >= 1",
    "@ <= 65535"
]
declarators = [
    ["arduino" , "int @identifier = @0;"],
    ["c" , "int @identifier = @0;"]
]

[type.INT]
value = "@"
require = [
    "@ : Int"
]
declarators = [
    ["arduino" , "int @identifier = @0;"],
    ["c" , "int @identifier = @0;"]
]

[type.STR]
value = "@"
require = [
    "@ : String"
]
declarators = [
    ["arduino" , "char* @identifier = @0;"],
    ["c" , "char* @identifier = @0;"]
]

[type.FLOAT]
value = "@"
require = [
    "@ : Float"
]
declarators = [
    ["arduino" , "float @identifier = @0;"],
    ["c" , "float @identifier = @0;"]
]

[type.DOUBLE]
value = "@"
require = [
    "@ : Double"
]
declarators = [
    ["arduino" , "double @identifier = @0;"],
    ["c" , "double @identifier = @0;"]
]

[type.LONG]
value = "@"
require = [
    "@ : Long"
]
declarators = [
    ["arduino" , "long @identifier = @0;"],
    ["c" , "long @identifier = @0;"]
]

[type.CHAR]
value = "@"
require = [
    "@ : Char"
]
declarators = [
    ["arduino" , "char @identifier = @0;"],
    ["c" , "char @identifier = @0;"]
]

[type.BOOL]
value = "@"
require = [
    "@ : Boolean"
]
declarators = [
    ["arduino" , "bool @identifier = @0;"],
    ["c" , "int @identifier = @0;"]
]

[type.BASIC]
value = "@"
require = [
    "@ : Boolean || @ : Char || @ : Int || @ : Double || @ : Float || @ : Long || @ : String"
]