[component.input.digitalInput]
type = "INT"
[component.input.digitalInput.parameters]
pin = "INT"
[component.input.digitalInput.generators.arduino]
expr = "digitalRead(@pin)"
[component.input.digitalInput.generators.mbed]
global = "DigitalIn @id(p@pin);"
expr = "@id"

[component.input.analogInput]
type = "INT"
[component.input.analogInput.parameters]
pin = "INT"
[component.input.analogInput.generators.arduino]
expr = "analogRead(@pin)"
[component.input.analogInput.generators.mbed]
global = "AnalogIn @id(A@pin);"
expr = "@id"

[component.output.serial]
[component.output.serial.parameters]
rate = "INT"