project_name = "Example"
dependencies = [
    "apdl_type.toml",
    "apdl_component.toml"
]

[server.influxdb.server1]
ip = "160.98.61.150"
port = 8086
database = "example"

[source.arduino.arduino1]
id = "uno"

[input.digitalInput.temp]
pin = 1

[function.tf]
function = "tf_transform.apdl"

[communication.serial.arduinoSerial]
bauds = 9600

[wire.sourceInput.arduino1.rawTemp]
[wire.transform.rawTemp.tf.temp]
[wire.send.rawTemp.server1]